[package]
name = "steam_analytics"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
regex = "1"
lazy_static = "1"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
