version: '3'

tasks:
  wrun:
   cmd: watchexec -i "src/static/*" -w "./src/" -r cargo run
   desc: Run the project in watch mode

  wrun-release:
   cmd: watchexec -i "src/static/*" -w "./src/" -r cargo run --release
   desc: Run the project in watch mode
