version: '3'

tasks:
  wrun:
   cmd: cargo watch -x run
   desc: Run the project in watch mode

  wrun-release:
   cmd: cargo watch -x "run --release" -i "src/static/*"
   desc: Run the project in watch mode
